version: "Docker and DevContainer Demo"
services:
  flaskapp:
    build: 
      context: ./../
      dockerfile: dockerfiles/Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ../:/home/NRuser/flaskapp/